const basic_section = [
  {
    href: "/dashboard",
    icon: "tabler-home",
    exactMatch: false,
    laMenu: "ໜ້າຫຼັກ",
    enMenu: "Dashboard",
    laSection: "ຂໍ້ມູນຫຼັກ",
    enSection: "Manage data",
    permission: ["c", "r", "u", "d"],
    feature: "leasingIndex",
    __typename: "RoleMenu",
  },
  {
    href: "/customer",
    icon: "tabler-users",
    exactMatch: false,
    laMenu: "ລູກຄ້າ",
    enMenu: "Customer",
    laSection: "ຂໍ້ມູນພື້ນຖານ",
    enSection: "Basic information",
    permission: ["c", "r", "u", "d"],
    feature: "customer",
    __typename: "RoleMenu",
  },
  {
    href: "/roomArea",
    icon: "tabler-door",
    exactMatch: false,
    laMenu: "ຫ້ອງ",
    enMenu: "Room",
    laSection: "ຂໍ້ມູນພື້ນຖານ",
    enSection: "Basic information",
    permission: ["c", "r", "u", "d"],
    feature: "roomArea",
    __typename: "RoleMenu",
  },
  {
    href: "/zone",
    icon: "tabler-stairs",
    exactMatch: false,
    laMenu: "Zone",
    enMenu: "Zone",
    laSection: "ຂໍ້ມູນພື້ນຖານ",
    enSection: "Basic information",
    permission: ["c", "r", "u", "d"],
    feature: "zone",
    __typename: "RoleMenu",
  },
  {
    href: "/role/list",
    icon: "tabler-shield-lock",
    exactMatch: false,
    laMenu: "ການຈັດການສິດທິ",
    enMenu: "Role Management",
    laSection: "ການຕັ້ງຄ່າ",
    enSection: "Settings",
    permission: ["c", "r", "u", "d"],
    feature: "user",
    __typename: "RoleMenu",
  },
  {
    href: "/category",
    icon: "tabler-category",
    exactMatch: false,
    laMenu: "ໝວດໝູ່",
    enMenu: "Category",
    laSection: "ຂໍ້ມູນພື້ນຖານ",
    enSection: "Basic information",
    permission: ["c", "r", "u", "d"],
    feature: "category",
    __typename: "RoleMenu",
  },
];

const settings_section = [
  {
    href: "/language",
    icon: "tabler-language",
    exactMatch: false,
    laMenu: "ພາສາ",
    enMenu: "Language",
    laSection: "ການຕັ້ງຄ່າ",
    enSection: "Settings",
    permission: ["c", "r", "u", "d"],
    __typename: "RoleMenu",
  },
];

export const roleStatic = {
  data: {
    Role: {
      _id: "67643abba78e121bcea07a53",
      createdAt:
        "Thu Dec 19 2024 15:24:43 GMT+0000 (Coordinated Universal Time)",
      updatedAt:
        "Thu Dec 19 2024 15:24:43 GMT+0000 (Coordinated Universal Time)",
      laName: "Super Admin",
      enName: "Super Admin",
      systemCode: "Supper",
      menus: [...basic_section, ...settings_section],
      __typename: "Role",
    },
  },
};
